"""empty message

Revision ID: 1ad5cf258b2b
Revises: bc8b1d64b3a4
Create Date: 2018-11-11 10:34:40.871473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ad5cf258b2b'
down_revision = 'bc8b1d64b3a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('bid', sa.Integer(), nullable=False),
    sa.Column('bname', sa.String(length=128), nullable=True),
    sa.Column('surplus', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('bid')
    )
    op.create_table('categories',
    sa.Column('cateid', sa.Integer(), nullable=False),
    sa.Column('bid', sa.Integer(), nullable=True),
    sa.Column('pricateid', sa.Integer(), nullable=True),
    sa.Column('pricatename', sa.String(length=64), nullable=True),
    sa.Column('subcateid', sa.Integer(), nullable=True),
    sa.Column('subcatename', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['bid'], ['brands.bid'], ),
    sa.PrimaryKeyConstraint('cateid')
    )
    op.create_table('products',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('bid', sa.Integer(), nullable=False),
    sa.Column('pname', sa.String(length=64), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('pdate', sa.Date(), nullable=True),
    sa.Column('cateid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bid'], ['brands.bid'], ),
    sa.ForeignKeyConstraint(['cateid'], ['categories.cateid'], ),
    sa.PrimaryKeyConstraint('pid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    op.drop_table('categories')
    op.drop_table('brands')
    # ### end Alembic commands ###
