"""empty message

Revision ID: c9878e1855ae
Revises: 09bb59676c53
Create Date: 2018-11-11 11:27:53.118609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9878e1855ae'
down_revision = '09bb59676c53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('bid', sa.Integer(), nullable=False),
    sa.Column('bname', sa.String(length=128), nullable=True),
    sa.Column('surplus', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('bid')
    )
    op.create_table('categories',
    sa.Column('cateid', sa.Integer(), nullable=False),
    sa.Column('bid', sa.Integer(), nullable=True),
    sa.Column('pricateid', sa.Integer(), nullable=True),
    sa.Column('pricatename', sa.String(length=64), nullable=True),
    sa.Column('subcateid', sa.Integer(), nullable=True),
    sa.Column('subcatename', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['bid'], ['brands.bid'], ),
    sa.PrimaryKeyConstraint('cateid')
    )
    op.create_table('products',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('bid', sa.Integer(), nullable=False),
    sa.Column('pname', sa.String(length=64), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('pdate', sa.Date(), nullable=True),
    sa.Column('cateid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bid'], ['brands.bid'], ),
    sa.ForeignKeyConstraint(['cateid'], ['categories.cateid'], ),
    sa.PrimaryKeyConstraint('pid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    op.drop_table('categories')
    op.drop_table('brands')
    # ### end Alembic commands ###
