"""empty message

Revision ID: f91bfda0d110
Revises: fc69e39a1e01
Create Date: 2018-11-11 10:00:29.278490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f91bfda0d110'
down_revision = 'fc69e39a1e01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('cateid', sa.Integer(), nullable=False),
    sa.Column('bid', sa.Integer(), nullable=True),
    sa.Column('pricateid', sa.Integer(), nullable=True),
    sa.Column('pricatename', sa.String(length=64), nullable=True),
    sa.Column('subcateid', sa.Integer(), nullable=True),
    sa.Column('subcatename', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['bid'], ['brands.bid'], ),
    sa.PrimaryKeyConstraint('cateid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories')
    # ### end Alembic commands ###
