"""empty message

Revision ID: fc69e39a1e01
Revises: 
Create Date: 2018-11-11 09:53:27.536317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc69e39a1e01'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('bid', sa.Integer(), nullable=False),
    sa.Column('bname', sa.String(length=128), nullable=True),
    sa.Column('surplus', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('bid')
    )
    op.add_column('customers', sa.Column('birthday', sa.Date(), nullable=True))
    op.drop_column('customers', 'birthdate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('birthdate', sa.DATE(), nullable=True))
    op.drop_column('customers', 'birthday')
    op.drop_table('brands')
    # ### end Alembic commands ###
